### await

###### 错误处理
当await 后面的promise 出现错误的时候 给该promise 添加一个catch 则不会出现代码异常停止运行
